spring:                                                         # 表示该配置直接为Spring容器负责处理
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 配置当前要使用的数据源的操作类型那个
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://47.101.169.28:3307/blog?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: ao-mysql
    filters: stat,wall,log4j                                    # druid监控配置
    dbcp2:
      validation-query: SELECT 1                                # 验证连接是否可用，使用的SQL语句
      test-while-idle: true                                     # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      test-on-borrow: false                                     # 借出连接时不要测试，否则很影响性能
      time-between-eviction-runs-millis: 30000                  # 每30秒运行一次空闲连接回收器
      min-evictable-idle-time-millis: 1800000                   # 池中的连接空闲30分钟后被回收,默认值就是30分钟。
      num-tests-per-eviction-run: 3                             # 在每次空闲连接回收器线程(如果有)运行时检查的连接数量，默认值就是3.
      min-idle: 5                                               # 数据库连接池的最小维持连接数
    　initial-size: 5                                           # 初始化提供的连接数
    　max-total: 5                                              # 最大的连接数
    　max-wait-millis: 200                                      # 等待连接获取的最大超时时间

jwt:
  config:
    key: kuailefeizhaijidi.plus
    ttl: 72000000